spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=GMT%2B8&useSSL=false
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: conetnt-center


server:
  port: 8090

#细粒度配置-配置属性方式
#user-center:
#  ribbon:
#    NFLoadBaLancerRuleclassName: com.netflix.loadbalancer.RandomRule

# 开启饥饿加载
ribbon:
  eager-load:
    clients: user-center
    enabled: true