spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=GMT%2B8&useSSL=false
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    #    nacos配置地址
    nacos:
      discovery:
        server-addr: localhost:8848
    #        服务名称
    application:
      name: content-centos
server:
  port: 8090